version: "3.8"

services:
  db:
    image: postgres:15
    container_name: superset_db
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    ports:
      - "5432:5432"
    volumes:
      - superset_db_data:/var/lib/postgresql/data

  superset:
    image: apache/superset:latest
    container_name: superset_app
    environment:
      DATABASE_URL: postgresql+psycopg2://superset:superset@db:5432/superset
      SUPERSET_LOAD_EXAMPLES: "yes"
      ADMIN_USERNAME: admin
      ADMIN_FIRST_NAME: Admin
      ADMIN_LAST_NAME: User
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin
    ports:
      - "8088:8088"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8088/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  superset_db_data:
